name: mlmnist Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup tools (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Print system info
        run: |
          echo "Running on OS: ${{ matrix.os }}"
          uname -a

      - name: Download MNIST dataset
        run: |
          set -e
          mkdir -p mnist_data
          cd mnist_data
          echo "Downloading MNIST files into $(pwd)"
          
          # Use curl directly as it is available on all runners
          curl -sS -L -o train-images.idx3-ubyte \
            "https://raw.githubusercontent.com/mrgloom/MNIST-dataset-in-different-formats/master/data/Original%20dataset/train-images.idx3-ubyte"
          curl -sS -L -o train-labels.idx1-ubyte \
            "https://raw.githubusercontent.com/mrgloom/MNIST-dataset-in-different-formats/master/data/Original%20dataset/train-labels.idx1-ubyte"
          curl -sS -L -o t10k-images.idx3-ubyte \
            "https://raw.githubusercontent.com/mrgloom/MNIST-dataset-in-different-formats/master/data/Original%20dataset/t10k-images.idx3-ubyte"
          curl -sS -L -o t10k-labels.idx1-ubyte \
            "https://raw.githubusercontent.com/mrgloom/MNIST-dataset-in-different-formats/master/data/Original%20dataset/t10k-labels.idx1-ubyte"
          cd ..
          
      - name: Build project library
        run: |
          make clean || true
          make all
          ls -all lib || true
      
      - name: Build project executable
        run: |
          make build || true
          ls -all bin || true

      - name: Run info target
        run: make info